# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahernand <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/07 15:26:11 by ahernand          #+#    #+#              #
#    Updated: 2022/06/07 15:26:13 by ahernand         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'

services:

  nginx:

    build:
      context: . 
      dockerfile: ./requirements/nginx/Dockerfile
    container_name: my_nginx

    image: my_nginx

    ports:
      - "443:80"




  db:
  

    #volumes:
    #  - nx_data:???

#volumes:
  #data: {}













































# This works for my_nginx 




#version: '3'

#services:

#  nginx:
#    image: nginx

#    ports:
#      - "80:80"

#    #volumes:
#    #  - nx_data:???

##volumes:
#  #data: {}












































































#version: "3.9"

#services:
#  # ______ MariaDB ______ #

#  db:
#    image: mysql:5.7

#    volumes:
#      - db_data:/var/lib/mysql

#    restart: always

#    environment:
#      MYSQL_ROOT_PASSWORD: somewordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress




#  # ______ Wordpress ____ #

#  wordpress:
#    depends_on:
#      - db

#    image: wordpress:latest

#    volumes:
#      - wordpress_data:/var/www/html

#    ports:
#      - "8000:80"

#    restart: always
    
#    environment:
#      WORDPRESS_DB_HOST: db
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress

#volumes:
#  db_data: {}
#  wordpress_data: {}
