# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahernand <ahernand@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/07 15:26:11 by ahernand          #+#    #+#              #
#    Updated: 2022/06/09 16:06:46 by ahernand         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.9"

services:

  # ______ Nginx ________ #

  nginx:

    depends_on:
      - wordpress

    build:
      context: . 
      dockerfile: ./requirements/nginx/Dockerfile

    container_name: nginx

    image: nginx

    ports:
      - "443:80"

    volumes:
      - v_wp:/var/www/html

    networks:
      - my_network




  # ______ MariaDB ______ #

  db:
    env_file:
      - .env

    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile

    container_name: mariadb

    image: mariadb
    restart: always
    volumes:
      - v_db:/var/lib/mysql

    networks:
      - my_network




  # ______ Wordpress ______ #

  wordpress:

    depends_on:
      - db

    ports:
      - "9000:9000"

    env_file:
      - .env
 
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile

    container_name: wordpress

    image: wordpress
    restart: always
    volumes:
      - v_wp:/var/www/html
      - v_db:/var/lib/mysql

    networks:
      - my_network

volumes:
  v_wp: {}
  v_db: {}
#    #driver_opts:
#    #o: bind
#    #type: none
#    #device: /Users/ahernand/Downloads/volume_mariadb

networks:
  my_network: {}











































































































































































































































































































































#version: "3.9"

#services:
#  # ______ MariaDB ______ #

#  db:
#    image: mysql:5.7

#    volumes:
#      - db_data:/var/lib/mysql

#    restart: always

#    environment:
#      MYSQL_ROOT_PASSWORD: somewordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress




#  # ______ Wordpress ____ #

#  wordpress:
#    depends_on:
#      - db

#    image: wordpress:latest

#    volumes:
#      - wordpress_data:/var/www/html

#    ports:
#      - "8000:80"

#    restart: always
    
#    environment:
#      WORDPRESS_DB_HOST: db
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress

#volumes:
#  db_data: {}
#  wordpress_data: {}